#!/usr/bin/env ruby

$:.unshift "./lib"
require 'cli_parser'
require "yaml"
require "ohanakapa"
require "ebt_uploader"
require "command_runner"

secrets = OpenStruct.new(YAML.load_file "config/secrets.yml")
Ohanakapa.configure do |config|
  config.api_endpoint = secrets.api_endpoint
  config.api_token = secrets.api_token
end

args = CliParser.new.args
runner = CommandRunner.new(args)
runner.run
